name = "nekok500-com"
compatibility_date = "2025-06-24"
account_id = "c8ddecea1f50caddfdbc21cbf0aadd4e"

[assets]
directory = "./dist"

[[routes]]
pattern = "nekok500.dev/*"
zone_id = "d922cd7d6c15256d1c5816164aed2c96"
