name = "nekok500-com"
compatibility_date = "2025-06-24"
account_id = "c8ddecea1f50caddfdbc21cbf0aadd4e"

[assets]
directory = "./dist"

[[routes]]
pattern = "nekok500.com/*"
zone_id = "265b017b4ca92ecc876c85bf935995fe"
